backend:
  image:
    repository: ctxgo/go-file-server
    tag: latest
    pullPolicy: IfNotPresent

  nodeSelector: {}

  tolerations:
    # - operator: Exists
  existingConfigMap: go-file-server

  persistence:
    enabled: true
    existingClaim: ""
    #storageClass: "ceph-filesystem"
    accessModes:
      - ReadWriteOnce
    size: 20Gi
    # PVC的Annotations
    annotations: {}
    # annotations:
    #   volume.beta.kubernetes.io/storage-provisioner: fuseim.pri/ifs
    # PVC的Labels
    labels: {}
    # 为pvc选取一个事先存在的pv
    selector: {}
    # selector:
    #   matchLabels:
    #     app: my-app
    # Mount path of app data volume
    mountPath: /basedir

  service:
    # ClusterIP|NodePort|LoadBalancer
    # type: NodePort 
    ports:
      # name不要修改，被ingress依赖
      - name: http
        containerPort: 9090
      #  nodePort: 39090
        protocol: TCP
      # # ftp监听端口(和程序实际配置的端口保持一致)
      # - name: ftp-32121
      #   containerPort: 32121
      #   nodePort: 32121
      #   protocol: TCP
      # # ftp被动端口
      # # 生产环境中不建议开通过多的被动端口，最佳实践是用 LoadBalancer
      # - name: ftp-32122
      #   containerPort: 32122
      #   nodePort: 32122
      #   protocol: TCP
      # # ftp被动端口
      # - name: ftp-32123
      #   containerPort: 32123
      #   nodePort: 32123
      #   protocol: TCP
      #   # ftp被动端口
      # - name: ftp-32124
      #   containerPort: 32124
      #   nodePort: 32124
      #   protocol: TCP
      #   # ftp被动端口
      # - name: ftp-32125
      #   containerPort: 32125
      #   nodePort: 32125
      #   protocol: TCP
    # type: LoadBalancer
    # annotations:
    #   lb.kubesphere.io/v1alpha1: openelb
    #   protocol.openelb.kubesphere.io/v1alpha1: layer2
    #   eip.openelb.kubesphere.io/v1alpha2: eip-pool
    # #固定虚拟ip
    # loadBalancerIP: x.x.x.x

  deployment:
    kind: Deployment

  # 亲和性策略
  # affinity:
  #   nodeAffinity:
  #     matchExpressions:
  #       key: foo
  #       operator: In
  #       values:
  #         - bar


  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 50m
      memory: 500Mi

  # 就绪性探针，用于判断容器是否准备好处理请求
  readinessProbe:
    initialDelaySeconds: 10
    successThreshold: 1
    failureThreshold: 3
    timeoutSeconds: 10
    periodSeconds: 5
    tcpSocket:
      port: 9090

  # 生存性探针，用于判断容器是否正常运行
  livenessProbe:
    initialDelaySeconds: 10
    successThreshold: 1
    failureThreshold: 3
    timeoutSeconds: 10
    periodSeconds: 5
    # 原http接口为: /actuator/health
    tcpSocket:
      port: 9090

  env:
    - name: TZ
      value: Asia/Shanghai


frontend:
  image:
    repository: ctxgo/go-file-server-ui
    tag: latest
    pullPolicy: IfNotPresent

  service:
    ports:
      # name不要修改，被ingress依赖
      - name: http
        containerPort: 80
        protocol: TCP

  deployment:
    kind: Deployment

  # 亲和性策略
  # affinity:
  #   nodeAffinity:
  #     matchExpressions:
  #       key: foo
  #       operator: In
  #       values:
  #         - bar

  resources:
    limits:
      cpu: 500m
      memory: 2816Mi
    requests:
      cpu: 20m
      memory: 1792Mi

  # 就绪性探针，用于判断容器是否准备好处理请求
  readinessProbe:
    initialDelaySeconds: 5
    successThreshold: 1
    failureThreshold: 3
    timeoutSeconds: 2
    periodSeconds: 2
    tcpSocket:
      port: 80

  # 生存性探针，用于判断容器是否正常运行
  livenessProbe:
    initialDelaySeconds: 5
    successThreshold: 1
    failureThreshold: 3
    timeoutSeconds: 2
    periodSeconds: 2
    tcpSocket:
      port: 80

  env:
    - name: TZ
      value: Asia/Shanghai


ingress:
  enabled: true
  #className: nginx
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  hosts:
    - host: file.example.com
      service: backend
      backendPort: 9090
      paths:
        - path: /api
          pathType: Prefix
    - host: file.example.com
      service: frontend
      backendPort: 80
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: file.example.com


# ingressRoute:
#   enabled: false
#   # annotations:
#   #   for: bar
#   entryPoints:
#     - web
#     - websecure
#   hostName: example.com
#   expose:
#     - service: backend
#       pathPrefix: /api
#       targetPort: 9090
#     - service: frontend
#       pathPrefix: /
#       targetPort: 80
#   tls:
#      secretName: example-tls




