application:
    # 服务器ip，默认使用 0.0.0.0
    host: 0.0.0.0
    # 端口号
    port: 9090 # 服务端口号
    #工作目录
    basedir: "/basedir"

logger:
    #日志位置
    path: "/var/log"
    # 日志等级 debug, info, warn, error, fatal
    level: debug

jwt:
    # token 密钥，生产环境时及的修改
    secret: testxxx
    # token 过期时间 单位：分
    timeout: 3600
database:
    # 数据库类型 mysql, postgres
    # sqlserver: sqlserver://用户名:密码@地址?database=数据库名
    driver: mysql
    # 数据库连接字符串 mysql 缺省信息 charset=utf8&parseTime=True&loc=Local&timeout=1000ms
    source: root:yourpassword@tcp(mysql-headless:3306)/dev?charset=utf8&parseTime=True&loc=Local&timeout=1000ms
cache:
    redis:
      addr: redis-headless:6379
      password: yourpassword
      db: 2

