application:
    # 服务器ip，默认使用 0.0.0.0
    host: 0.0.0.0
    # 端口号
    port: 9090 # 服务端口号
    #工作目录
    basedir: "/basedir"

logger:
    #日志位置
    path: "./log"
    # 日志等级 debug, info, warn, error, fatal
    level: debug

jwt:
    # token 密钥，生产环境时及的修改
    secret: testxxx
    # token 过期时间 单位：分
    timeout: 3600
    
database:
    # 数据库类型 mysql, postgres
    # sqlserver: sqlserver://用户名:密码@地址?database=数据库名
    driver: mysql
    # 数据库连接字符串 mysql 缺省信息 charset=utf8&parseTime=True&loc=Local&timeout=1000ms
    source: root:yourpassword@tcp(127.0.0.1:3306)/dev?charset=utf8&parseTime=True&loc=Local&timeout=1000ms

#缓存配置，默认使用内存，如果去掉注释则使用redis
cache:
#    redis:
#      addr: 127.0.0.1:6379
#      password: xxxxxx
#      db: 2

# dex(ldap)认证相关配置
oauth:
  # 是否开启dex认证
  enable: false
  # 和 dex config.staticClients配置中的id一致
  clientID: "go-file-server-id"
  # 和 dex config.staticClients配置中的secret一致
  clientSecret: "ZXhhbXBsZS1hcHAtc2VjcmV0"
  # dex认证url, 该地址需要能被客户端访问, 建议配置到nginx代理中
  # 和 dex config配置中的issuer一致
  issuerUrl: "http://127.0.0.1:9000/dex"
  # dex认证成功后回调地址，这里配置的前端地址拼接/login/callback
  # 和 dex config.staticClients配置中的redirectURIs一致
  redirectUrl: "http://127.0.0.1:9000/login/callback"
  # dex grpc连接方式，用于获取connectors中ladp连接
  grpc:
    addr: "127.0.0.1:5557"
    # 如果未提供SSL凭证，则dex将以明文（HTTP）连接.
    # tlsCert: /etc/dex/grpc.crt
    # tlsKey: /etc/dex/grpc.key
    # # Client auth CA.
    # tlsCA: /etc/dex/client.crt
  #一个自定义字符串，用于回调验证，防止 CSRF 攻击
  state: "helloword"
  scopes:
    - "openid"
    - "profile"
    - "email"
    - "offline_access"
    - "groups"

ftp:
  enable: false
  addr: :32121
  passivePortStart: 32122
  passivePortEnd: 32125
#  publicHost: yourhost
